version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.3.2
    container_name: localstack_demo
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"